### ISSUE TITLE
Email API not found

### ISSUE THREAD

**Issue by FelixFuin** [gunjandatta/sprest#125]
Hi,

In a previous release of sprest i was using $REST.Email but I can't find it in this release. Is it going to be replaced by something else ?

Thanks!

**Comment by gunjandatta** [comment]
Refer to [this post](https://github.com/gunjandatta/sprest/releases/tag/2.3.7) for details of the Email lib moving to the Utilities lib. I've updated the [wiki](https://gunjandatta.github.io/api/utility) to give details of how to use it as well. Hope this info helps. Please close this out if this answers your question. If you have other questions/issues, please let me know and I'll happily assist.

**Comment by FelixFuin** [comment]
This help a lot! Thanks and great job!
But the sendEmail method create an issue...
"r.addMethods is not a function" in Utility.js line 35

Do you have any ideas ? thanks

**Comment by gunjandatta** [comment]
I ran "$REST.__ver" to see what version is running. In my case it's v3.49. In O365, I ran the following from the browser console:

$REST.Utility().sendEmail({ To: "me@dattabase.com", Subject: "Test Email", Body: "<h1>Test</h1><p>This is a test email</p>"}).executeAndWait()

This successfully sent an email. If you could help provide additional info, so I can try to recreate on my side; I'll do my best to help troubleshoot.

Thanks

**Comment by FelixFuin** [comment]
Thanks,

In the chrome console everything works fine but I have the same error in my React app (16.2)

- I updated Sprest to 3.49

**Comment by gunjandatta** [comment]
I'm unsure what the error is in the React app. Is the issue happening when building the solution? How are you referencing the library? Is this a JSX or TypeScript solution? Can you send the code snippet, so I can help troubleshoot?

**Comment by gunjandatta** [comment]
I updated a test JS project I have, importing the latest gd-sprest library. I've imported both the Utility and $REST components from the library to test sending an email. Both worked successfully, so I'm not sure how to recreate the issue you are having. Below is a code example of what I did. Please provide a code example to help recreate the issue, so I can help troubleshoot further. Thanks.

TypeScript Example
```
import { $REST } from "gd-sprest";

// Send an email
$REST.Utility().sendEmail({
  To: ["me@dattabase.com"],
  Subject: "Test EMail",
  Body: "<h1>Test Email</h1><p>This is a test email.</p>"
}).execute(() => {
  // Add a notification
  Helper.SP.Notify.addNotification("Email was sent successfully.");
});
```

**Comment by FelixFuin** [comment]
Hi !

Everything works fine.. An import of $REST instead of a require did the trick.. No more "addMethods error".

Thanks again for your perfect support, have a nice day ! 
I will close the issue.

**Comment by FelixFuin** [comment]
Hi,

I reopen the issue because it's not totally fixed.. An other problem stems from the first one..
Like I can't get the library using require (It will cause bugs with addMethods in Utility.sendEmail), I have to use Import.

I run my project locally to work faster (and to do some demo page) with JSON files instead of SharePoint Lists. I can't run my React project with a `npm run start` because `import { $REST} from 'gd-sprest` is generating an error..  
("SP in not defined in Rest.js => SP ? SP.SOD.notifyScriptLoadedAndExecuteWaitingJobs("gd-sprest.js") : null;)

Is there a way to test locally ?

Thanks a lot

**Comment by gunjandatta** [comment]
Refer to the [code examples](https://gunjandatta.github.io/api/utility-code) page for examples of how to use this feature. Please let me know how you are referencing it:

### Browser
```html
<script type="text/javascript" src="/siteassets/gd-sprest.min.js"><script>
<script type="text/javascript">
// Use the global variable
$REST.Utility.sendEmail({...})
</script>
```
### JavaScript
```js
var $REST = require("gd-sprest");
$REST.Utility.sendEmail({...})
```
### TypeScript
```ts
import { Utility } from "gd-sprest"
(new Utility()).sendEmail({...})
```

**Comment by gunjandatta** [comment]
Nevermind, I think I see the issue you are having.

**Comment by gunjandatta** [comment]
Use v3.5.3 and you should be good to go. I updated that line to be:

SP && SP.SOD ? SP.SOD.execute....

Let me know if you are still having issues.

**Comment by FelixFuin** [comment]
I updated to v3.5.3 but I still have the same issue with the line `SP && SP.SOD ? SP.SOD.notifyScriptLoadedAndExecuteWaitingJobs("gd-sprest.js") : null;`

I use `import {Web, Utility} from 'gd-sprest';`

Thanks for your support

**Comment by gunjandatta** [comment]
I was finally able to reproduce the issue. Target version v3.5.5 should fix your issue.

Let me know if you have any other issues.

**Comment by FelixFuin** [comment]
You're great!

It works perfectly on localhost and on SharePoint, thanks for your excellent support!

Have a good day!

**Comment by gunjandatta** [comment]
Always happy to help out. Thank you for reporting this issue. Let me know if there are any other issues as you use the library.
