### ISSUE TITLE
addMethods is not a function

### ISSUE THREAD

**Issue by danawesome** [gunjandatta/sprest#148]
The error I'm encountering is this:
```
>VueJSDemo.Configuration.List.createTestData()
demo-vue.js:formatted:10030 Creating the items.
demo-vue.js:formatted:18896 Uncaught TypeError: i.addMethods is not a function
    at Object.t [as List] (demo-vue.js:formatted:18896)
    at Object.s.List.createTestData (demo-vue.js:formatted:10031)
    at <anonymous>:1:30
```
This error appears when using the directions from http://dattabase.com/sharepoint-2013-modern-webpart-3-4/
In Step 2 substep "5) Add the test data" is when the error happens. 
`VueJSDemo.Configuration.List.createTestData()`
I have found this to be the case in SharePoint Online and SharePoint 2013 on-prem

Any help with this would be appreciated.

**Comment by gunjandatta** [comment]
Thanks for reporting this. The issue was with the import statement in the cfg.js file.
```
var $REST = require("gd-sprest");
```
should be
```
import { $REST } from "gd-sprest";
```
The blog post and github projects have been udpated. Please let me know if you have any other issues.

**Comment by gunjandatta** [comment]
Making another tweak to the list add item method. There was an extra parameter that didn't need to be there.

**Comment by gunjandatta** [comment]
This actually led to an issue w/ the $REST object not containing some of the new configuration types too. Thanks for reporting this issue. Do an "npm update" in your current project to get the latest and you should be good to go.

**Comment by gunjandatta** [comment]
Please let me know if this is working so I can close this issue out.

**Comment by gunjandatta** [comment]
I'm going to close this one out, but please re-open it if you have issues or questions. I've tested this in SPO and am no longer able to recreate the issue.

Thanks again for reporting it.
