### ISSUE TITLE
Update List item always fails with 400 bad request

### ISSUE THREAD

**Issue by bcobra** [gunjandatta/sprest#177]
Code:
 List("ProcLineItems").Items(iID).update({
        RejectionFeedback: "test"   
    }).execute(()=>{ 
        alert("Rejection feedback sent to requester.");    
        
    });    

get same response no matter what field i try and update. iID is a number field with the correct ID

**Comment by gunjandatta** [comment]
What version of the library are you using? I believe I just fixed this recently.

**Comment by gunjandatta** [comment]
v4.1.9 has the fix for this, but I would get v4.2.0.

**Comment by bcobra** [comment]
latest fix did the trick. Thanks for all your hard work!
