### ISSUE TITLE
Get Term tree structure by term name

### ISSUE THREAD

**Issue by prasadregula** [gunjandatta/sprest#193]
How i can able to get complete tree structure of the team by name.

**Comment by gunjandatta** [comment]
Thanks for posting this question. I've gone ahead and updated the [help page](https://gunjandatta.github.io/helpers/taxonomy) related to taxonomy. I hope this updated info will help answer your question. Seeing as there are many ways to get the terms, you will first need to get the data and then use the ```toObject``` method to convert it to a tree.

If you know the target group name, then use the ```getTermsByGroupName(name:string, groupName:string)``` method to get the terms. If the data is in the default site collection's term group, then you can use the ```getTermsFromDefaultSC(name:string)``` method to get the terms from the default site collection's group. Once you have the data, you can convert it to a tree using the ```toObject(terms:Array<ITermInfo>)``` method.

Refer to the updated [help page](https://gunjandatta.github.io/helpers/taxonomy) for additional info. Please close this issue if it resolves your question.

**Comment by prasadregula** [comment]
Thanks I can able to get all terms. But, I need to pass the termset . But i have managed meta data ield which has term value. Based on that value i need to find the complete tree. I think i can use findByName(term: ITerm, termName: string). But how I can pass the ITerm value.

**Comment by gunjandatta** [comment]
Refer to the updated [help page](https://gunjandatta.github.io/helpers/taxonomy) and reference the "Getting a Term Set" section to see examples. From there you can convert it to an object and search for your term, and use the findByName method to find the term. The term returned is still a tree object, so you should have all of your data.

**Comment by gunjandatta** [comment]
Did you still need any help on this issue? Since you have the terms as an array, you would use the ```toObject``` method to convert it to an object, and then pass it to the ```findByName``` method. Please refer to the help page in the previous comment, since there may be a method for getting the data for your solution.

If you are still having issues, please let me know so I can further assist.

**Comment by gunjandatta** [comment]
Please re-open this issue if the help provided didn't resolve the issue.
