### ISSUE TITLE
Skip Option Not Passed to REST Query

### ISSUE THREAD

**Issue by sky-gregory** [gunjandatta/sprest#220]
When using the following query, I don't see the Skip parameter passed to SharePoint

SP Network Call:
[SP URL]/_api/web/lists/getByTitle('LPI-Vols-20190901')/Items?$select=ID,Title&$orderby=ID&$top=3000

Code:
```Javascript
$REST.List(sourceList)
.Items()
.query({
    Top: 3000,
    Select: ["ID", "Title"],
    OrderBy: ["ID"],
    Skip: currentInt || 0
})
.execute(function (response) {
    records = response.results;
})
```

**Comment by gunjandatta** [comment]
Based on the code, if "0" is passed as the value then the "$skip" value will not be added to the call. If you send a value > 0, then it will be added to the call.

Is this logic causing issues?
