### ISSUE TITLE
Query List with internal name

### ISSUE THREAD

**Issue by johannes-z** [gunjandatta/sprest#26]
`/_api/web/lists` exposes the `d:EntityTypeName` property for all lists. By querying `/_api/web/_lists` first, you could select the `d:Title` of the list that matches the `EntityTypeName` and then make the call to `/_api/web/lists/getbytitle('...')`.

The downside is to have 2 calls per list site query, but then you don't have any troubles adapting your code if you change the display name.

**Comment by gunjandatta** [comment]
/_api/web/lists is the same as _api/lists right?

I do like the idea of being able to get it by the entity type name, but the library is built to work w/ the api based on how Microsoft designed it. The code below will show you how to do this in one call, but because it returns a list collection not a list object I can't really use it. I'm open to thoughts or ideas on this, so let me know what you think.

```
// Get the current web
(new $REST.Web())
  // Get the lists
  .Lists()
  // Query for the 'Site Assets' library
  .query({
     Filter: "EntityTypeName eq 'SiteAssets'",
     Top: 1
  })
  // Execute the request
  .execute((lists:Types.ILists) =>{
     let list = lists.existsFl ? lists.results[0] : null;
     if(list) {
       // Code goes here
     }
  });
```

**Comment by johannes-z** [comment]
Yes, I believe it's the same.

This is actually what I was proposing. You query all lists, filter by the internal name you pass to the function, and get the list back. `(new $REST.Web()).List('<internalName>')` could be an alias for the exact same call. But in the `execute` callback you'd get a single list or `null`. Something of the lines of:

```js
// Get the current web
(new $REST.Web())
  // Query for the 'Site Assets' library
  .List('SiteAssets')
  // Maybe an optional query chain command to specify additional columns etc.
  // Execute the request
  .execute((list:Types.IList) => {
     // do something with list
  });

It's less code, and looks less hacky in my opinion. 

I don't get why you can't use it though. I know `/web/lists` returns a list collection, but you need the collection anyway to filter by the `EntityTypeName`. This is same thing I'm doing now with the JSOM -> get all lists, include the `EntityTypeName` column, and check if a list with the given internal name exists. That requires two calls to the REST API, whilst your solution only requires one, which is even better.

**Comment by gunjandatta** [comment]
The library initially converted collections containing 1 item from a collection to a single object, but then this broke other functionality when you wanted to develop against the collection. For instance, adding a new item to a collection failed when the collection only contained 1 item. I can try to add this logic back in for the "query" method only. Then the List object can be updated to do the following:

old code:
(new $REST.Web()).Lists('Site Assets') -> /_api/web/lists/getByTitle('Site%20Assets')

new code:
(new $REST.Web()).Lists('Site Assets') -> /_api/web/lists?$filter=Title eq 'Site%20Assets' or EntityTypeName eq 'Site%20Assets'&$top=1
(new $REST.Web()).Lists('SiteAssets') -> /_api/web/lists?$filter=Title eq 'SiteAssets' or EntityTypeName eq 'SiteAssets'&$top=1

The new logic will return a List object instead of a ListCollection object, which will work.

**Comment by johannes-z** [comment]
I'm not too familiar with your library yet, but I think the `or` could be dangerous. I'm not entirely sure, but I think the display name of another list could be the same as the internal name of another one (given, this is highly unlikely). 

I'm not sure if you would have to change how the library works. As I stated, a simple alias would do. But do whatever feels more consistent.

**Comment by gunjandatta** [comment]
I could add a Boolean flag to the List constructor called "displayNameFl" defaulted to "true". If set to false, then it'll search by Entity Name.

(new $REST.List("SiteAssets", false)).execute((list) => {
  // Code goes here
});

If you like this, then I'll update the library with this functionality.

**Comment by johannes-z** [comment]
Personally, I would prefer it the other way around, because querying by internal name seems to be a more common thing to do than querying by display name, but I'm fine with either. Also, I'm assuming that I would still be possible to chain the `List` with the `query` method to select/filter etc., right? 

Yes, this feature would be great! I really like what you've done so far and look forward to more features ;)

**Comment by gunjandatta** [comment]
Thanks. I'm testing out a static method, so you can just do:

```
$REST.List.getByEntityName("SiteAssets").done((list) => {
     // Code goes here
});
```
I've just added the "Configuration" which I feel will really help out. I'm not sure what you are trying to do, but the new configuration class may do it already. I plan to add content types to it when I some more free time. I just created a [blog post](http://dattabase.com/sharepoint-scripts-starter-project/) on this today.

**Comment by gunjandatta** [comment]
Ok. The library has been updated :)

```
// Asynchronous Request
$REST.List.getByEntityName("SiteAssets", (list:Types.IList) => {
  // Code goes here
});

// Synchronous Request
var list = $REST.List.getByEntityName("SiteAssets");

// Code goes here
```
Hope this helps you out and is the functionality you wanted. I've tested both methods in SharePoint Online. Thanks again for this request. This will be in the npm version 1.3.5. It's been pushed to GitHub.

I'll close out this issue, but feel free to reopen it if you have issues.

**Comment by johannes-z** [comment]
Something to consider: `getByEntityName` could/should return a promise, so you can implement something like this:

```js
var listNames = ['List1', 'List2']
var queries = listNames.map(listName => List.getByEntityName(listName))
Promise.all(queries).then(data => { console.log(data) })
```

Otherwise, you would have to wrap `List.getByEntityName` inside a function that returns a `Promise`. Possible, but inconvenient. I'm not sure how the rest of your API is defined though - so if this would break convention, there's no need to do it.

**Comment by gunjandatta** [comment]
The library has two methods:
execute - Asynchronous Request
executeAndWait - Synchronous Request (Really used when interacting with the library from the browser console)
This allows us to chain properties and gives the ability to execute at any point.
1) Get all lists (new $REST.Web()).Lists().execute(...)
2) Get list items (new $REST.List("list")).Items().query(...).execute(...)

You can chain multiple requests, refer to this [wiki page](https://github.com/gunjandatta/sprest/wiki/Full-Control-of-Request-Execution-Order) for additional information on the execution order.
```
// Get the list
var list = new $REST.List("My List");

// Add 5 items to the list, but execute them in order
// The "true" variable will wait for the previous request to complete before executing it
list.Items().add({ Title: "Item 1" }).execute(true);
list.Items().add({ Title: "Item 2" }).execute(true);
list.Items().add({ Title: "Item 3" }).execute(true);
list.Items().add({ Title: "Item 4" }).execute(true);
list.Items().add({ Title: "Item 5" }).execute(true);

// Wait for the requests to complete
list.done((item1, item2, item3, item4, item5) => {
  // Code goes here
});
```

You can refer to the [spConfig.js](https://github.com/gunjandatta/sprest/blob/master/src/lib/helper/spCfg.ts) class code for examples of using this technique.

Hope this info helps.

**Comment by gunjandatta** [comment]
I'll see if I can add another helper method or figure out how to implement a way to auto set the "query" of the collection.

**Comment by gunjandatta** [comment]
The getByEntityName is different since it's a static method and requires execution against the server, so the chaining doesn't really work like the others. Refer to the code example below:
```
List.getByEntityName("listEntityName", (list) => {
  // Get the items
  list.Items().execute((items) => { ... });
}, "optional site url, if null current web is targeted");
```

To help explain, the library is a url builder. The code below will demonstrate the url being built. No execution to the server occurs unless you specify it.
```
var list = new List("list name") -> https://[sp url]/_api/web/lists/getByTitle('list%20name')
var items = list.Items() -> https://[sp url]/_api/web/lists/getByTitle('list%20name')/items
var query = items.query({ Filter: "Title eq 'Test'" }) -> https://[sp url]/_api/web/lists/getByTitle('list%20name')/items?$filter=Title eq 'Test'

// The "query" object at this point can't be built upon

// Execute the request to get the items
// Only 1 request is executed against the server to get the items
query.execute((items) => {
  // Code goes here
});
```

If you take a look at the example code for the SPConfig class, it may help you out.

**Comment by gunjandatta** [comment]
I thought this may be related and useful. You can get the fields and items for a list in 1 request by doing the following:
```
// Get the current web
(new Web())
  // Get the lists
  .Lists()
  // Query for the list by the entity type name, and expand the fields and items
  .query({
     Expand: ["Items", "Fields"],
     Filter: "EntityTypeName eq '[List Entity Type Name]'"
  })
  .execute((lists) => {
     // Code goes here
     lists.results[0] -> List
     lists.results[0].Fields.results -> List Fields
     lists.results[0].Items.results -> List Items
  });
```

**Comment by johannes-z** [comment]
Looks great! I guess the `Items` queried are only the one visible on the default view? Most of the time additional metadata is required (e.g. `ListItemID`, `GUID`, `Author`, `FileType`, etc.).
Do you know if those can be queried in one go as well?

**Comment by gunjandatta** [comment]
You can select the "Items" property by doing the following:
```
// Get the current web
(new Web())
  // Get the lists
  .Lists()
  // Query for the list by the entity type name, and expand the fields and items
  .query({
     Expand: ["Items", "Fields"],
     Filter: "EntityTypeName eq '[List Entity Type Name]'",
     Select: ["*", "Items/ID", "Items/Title"]
  })
  .execute((lists) => {
     // Code goes here
     lists.results[0] -> List
     lists.results[0].Fields.results -> List Fields
     lists.results[0].Items.results -> List Items
  });
```

If you don't use the "*", then it will not return the other properties.

**Comment by gunjandatta** [comment]
Check out my latest [blog post](http://dattabase.com/sharepoint-rest-api-odata/) for more info on this. It has useful information and code examples.
