### ISSUE TITLE
Query List on different site collections

### ISSUE THREAD

**Issue by johannes-z** [gunjandatta/sprest#27]
I'm not sure if this is already implemented, but is there a way to pass the site collection as well? Right now, I think, it's only possible to query lists on the same site collection the user is on. There are usecases though, where you would want to query multiple lists from different site collections.

Basically this would be done like this: `List.getByEntityName(siteCollection, listName)`. 

The request would be: `https://<server>/<siteCollection>/_api/web/lists/....`

**Comment by gunjandatta** [comment]
I don't believe the REST api will let you do cross-site collection requests. The Web object takes a "url" property, so if you wanted to test this out:
```
(new $REST.Web("[relative url to the other site collection]")
  .Lists()
  .query({ Filter: "EntityTypeName eq '[List Entity Type Name]'" })
  .execute((list) => {
  });
```

This is where the live browser testing comes in handy. If you already have the library loaded on a page, press F-12 and go to the console.
```
(new $REST.Web("[url]").Lists().query({ Filter: "EntityTypeName eq '[list name]'" }).executeAndWait();
```

This is how I've tested and figured out bugs, by testing it out on the fly as I code the solution.

**Comment by gunjandatta** [comment]
I thought this was a restriction, but I guess I was wrong. I was able to get a list in the root "/" site collection from my "/sites/dev" site collection.

```
// Executed from the '/sites/dev' site collection
(new $REST.Web("/")).Lists("Site Assets").executeAndWait()
```

**Comment by gunjandatta** [comment]
You should be able to do this then:
$REST.List.getByEntityName("SiteAssets", null, "/");

The "targetInfo" object is explained [here](https://github.com/gunjandatta/sprest/wiki/Target-Information). The base object will detect a "string" or "object" types and defaults the string type as the target web url.

**Comment by johannes-z** [comment]
Ah, I see. Will have to try this though. I will reopen this issue if I come across any related problems. Thank you!
