### ISSUE TITLE
[Help Wanted] [Enhacement] Recursively check the Document Set for empty / checked out

### ISSUE THREAD

**Issue by mr-t-the-beerdrinker** [gunjandatta/sprest#273]
Hi guys,
I need to check the Document Set for an items, where the sub folders (recursively) are empty or contain only checked-out files.
Is it possible to query Files or Folders recursively using this library? Are there any best practices on this topic?

I'm doing now something like these steps:
1) Get all "Base" items (filtered by custom content type)
2) for each of the base items, check the direct files (if there are any or are all checked out)
3) if it passed the step 2 above, I need recursively check each of the folder (ideally one at a time, so only the lowest possible requests are trigerred (e.g. if first request returns non-checked out files, skip the item)

edit: code removed, not valid

**Comment by gunjandatta** [comment]
I have a document set in my dev SPO environment called "Doc Set Demo". I created a doc set item called "Test" which has the following folders/files:

Test/Document.aspx
Test/Folder
Test/Folder/Document.aspx
Test/Folder/SubFolder
Test/Folder/SubFolder/SubDocument.aspx
Test/Folder/SubFolder/SubSubFolder
Test/Folder/SubFolder/SubSubFolder/SubSubDocument.aspx

You can query the document library like this:

```ts
List("Doc Set Demo").Items().query({
  // Filter for document set items
  // I renamed the document set content type to "Dashboard Item" so update accordingly
  Filter: "ContentType eq 'Dashboard Item'",
  Expand: [
  ]
}).execute(({ results })=> {
  // Code goes here...
});
```

You are able to make live requests in the browser for testing, so take advantage of that.
![image](https://user-images.githubusercontent.com/18452035/111052775-0a3b0680-842c-11eb-8cc0-ced4eb539ccd.png)

**Comment by gunjandatta** [comment]
Refer to this [blog post](https://dattabase.com/blog/odata-expand) for a full overview.

**Comment by mr-t-the-beerdrinker** [comment]
But if I don’t know how many levels the hierarchy has, I still have to do it recursively, or?

**Comment by gunjandatta** [comment]
You can always try to expand it out a couple levels and make a recursive function. Is this for an environment where the batch request is available?

**Comment by mr-t-the-beerdrinker** [comment]
Yeah, I will then try couple of expands and we will see. I was thinking, If I could force it to maybe query the "sub-items" recursively, but I will figure something, thanks anyway, nice lib :)

**Comment by gunjandatta** [comment]
No need to close out the issue. I have a getWebs method that does something similar to your ask. Let me repurpose the function and test it out for what you want. That'll be a better example and if that helps, then close out the issue :0)

**Comment by mr-t-the-beerdrinker** [comment]
There's maybe one more thing. In typescript, you will receive ListItemOData, where you have Folder prop and you have to query for Files() / Folders() again. After then I can iterate Files and Folders collection. I have to check it, because then my recursion is not working. But if you will have some handy method you mentioned, I would like to have it ;) Thanks again for tips

**Comment by gunjandatta** [comment]
Why not simplify the OData query this way:

```ts
private function loadItems() {
  // Return a promise
  return new Promise((resolve, reject) => {
    // Query the list
    List("Doc Set Demo").Items().query({
      Expand: ["ContentType", "Folder", "File"],
      Select: ["ID", "Title", "ContentType/Name", "Folder/Name", "Folder/ServerRelativeUrl", "File/Name", "File/ServerRelativeUrl"],
      Top: 5000,
      GetAllItemsFl: true
    }).execute(({ results })=> {
      let docSetItems = [];
      let files = [];
      let folders = []

      for(var i=0; i<results.length; i++) {
        var item = results[i];

        // Add the item to the data array, based on the type
        if(item.ContentType.Name == "Folder") { folders.push(item); }
        else if(item.ContentType.Name == "Dashboard Item") { docSetItems.push(item); }
        else { files.push(item); }

        // Resolve the request
        resolve({ docSetItems, files, folders });
      }
    }, reject);
  });
}
```

![image](https://user-images.githubusercontent.com/18452035/111075234-5bdfa180-84bd-11eb-99a2-511cc18ea148.png)

**Comment by mr-t-the-beerdrinker** [comment]
thanks for all the ideas ;)

**Comment by gunjandatta** [comment]
I believe this code example will give you all of the files/folder/item information you are requesting, in an efficient way. If so, please close out this request and thank you for submitting it in the first place. I think this issue has a lot of great examples to help others out.

**Comment by mr-t-the-beerdrinker** [comment]
Thanks ;)
