### ISSUE TITLE
TypeScript Compilation Failures in Angular 12 App

### ISSUE THREAD

**Issue by jason-heiser** [gunjandatta/sprest#279]
I have the NPM package for gd-sprest@6.5.9 installed as a dependency in an Angular 12 app. This version of Angular uses TypeScript 4.3.5, which is having difficulties with gd-sprest.

When I import the Web object so I can use it for REST operations, for example:

`import { Web } from 'gd-sprest';`

This results in a bevy of compilation errors I have been unable to resolve. Here are some examples of the two major errors occurring: (A) “namespace not found” and (B) “cannot simultaneously extend types X and Y”.

`Error: node_modules/gd-sprest-def/lib/Microsoft/SharePoint/Comments/entitytypes.d.ts:81:79 - error TS2694: Namespace '"node_modules/gd-sprest-def/lib/SP/index"' has no exported member 'Microsoft'.
81  add(text?: SP.Microsoft.SharePoint.Comments.comment): Base.IBaseExecution<SP.Microsoft.SharePoint.Comments.comment>;`

`Error: node_modules/gd-sprest-def/lib/SP/Publishing/entitytypes.d.ts:509:18 - error TS2320: Interface 'IRepostPageQuery' cannot simultaneously extend types 'RepostPageOData' and 'RepostPageMethods'.
  Named property 'copy' of types 'RepostPageOData' and 'RepostPageMethods' are not identical.
509 export interface IRepostPageQuery extends RepostPageOData, RepostPageMethods {`

`Error: node_modules/gd-sprest-def/lib/SP/Publishing/entitytypes.d.ts:557:18 - error TS2320: Interface 'RepostPageOData' cannot simultaneously extend types 'SitePageOData' and 'RepostPageMethods'.
  Named property 'getVersion' of types 'SitePageOData' and 'RepostPageMethods' are not identical.
557 export interface RepostPageOData extends SP.Publishing.SitePageOData, Base.IBaseResult, RepostPageProps, RepostPageMethods {`

This is probably more of a “help wanted” issue, but I would greatly appreciate any assistance. Thank you.

**Comment by drewbombard** [comment]
OMG... I'm having the exact same issue!!

For what it's worth, I'm on Win10 through Visual Studio Code if that helps at all.  I doubt it, but just thought I'd add that tidbit.

**Comment by gunjandatta** [comment]
I'll try to recreate this issue today and report back.

**Comment by gunjandatta** [comment]
Can you help me recreate this. I have a simple hello world project w/ the package.json:

```json
{
  "name": "hw",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode=development",
    "prod": "webpack --mode=production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gd-sprest": "^6.5.9"
  },
  "devDependencies": {
    "@babel/core": "^7.10.0",
    "@babel/preset-env": "^7.10.0",
    "babel-loader": "^8.1.0",
    "ts-loader": "^7.0.5",
    "typescript": "4.3.5",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  }
}
```

The index.ts src file is a simple reference to the Web component:

```ts
import { Web } from "gd-sprest";

// Get th web information
Web().execute(web => {
    console.log("Web Title: " + web.Title);
});
```

This built fine, so I'm uncertain what the best way to recreate this error on my end is. Thank you @jason-heiser or @drewbombard for any help on recreating the issue.

**Comment by jason-heiser** [comment]
I have set up a repo with a bare bones Angular 12 installation that also uses gd-sprest.

https://github.com/jason-heiser/ng-sprest-test

Once you’ve cloned it and have installed everything with `npm install`,  execute `npm run start` to see the compilation issues.

**Comment by gunjandatta** [comment]
Thanks for setting this up. It's from the last update of metadata from the $REST API. I will work on this to resolve the errors.

**Comment by gunjandatta** [comment]
version 6.6.1 has the latest definitions that will compile.

I had to remove the last logic that added inheritance of the parent collection to help provide the correct intellisense. The logic was causing these issues when it's dealing w/ mulitple levels. I'm going to have to figure out a better way to inherit these.
