### ISSUE TITLE
List querying with top doesn't return all rows

### ISSUE THREAD

**Issue by johannes-z** [gunjandatta/sprest#28]
I've been trying out the List library, and came across a problem when using `GetAllItems: true` and `Top: x`. It returns only the amount of rows that I specify in `Top`.

```js
  var queryObj = {
    Select: _columns,
    Expand: _expand,
    Top: 2,
    GetAllItems: true
  }
```

```js
    List.getByEntityName(listName, list => {
      list.Items().query(queryObj).execute(items => {
        console.log(items)
     })
   }, site)
```

`items` logs only 2 items in this example, although there are a few more in the list. As per the docs I thought that the `execute` callback would only be called if all items have been queried and there is no `next` property anymore.

**Comment by gunjandatta** [comment]
Here is a link to the large list example project in GitHub: https://github.com/gunjandatta/sprest-large-list

I'll retest the above GitHub solution to see if there are any issues with the latest. If you have a sample list/example for recreating the issue, that would be helpful.

**Comment by johannes-z** [comment]
I've looked at that project before. I'll post a more complete example below. The `Promise` resolves as soon as the first batch of data arrives, rather than when all queries are completed. The requests are made correctly (the `__next` property is being used etc.), but the `items` in the `execute` callback only contain the first batch, as already described.

```js
  var queryObj = {
    Select: _columns,
    Expand: _expand,
    Top: 2,
    GetAllItems: true
  }

  return new Promise((resolve, reject) => {
    List.getByEntityName(listName, list => {
      list.Items().query(queryObj).execute(items => {
        console.log(items)
        resolve(items.d.results)
      })
    }, site)
  })
```

**Comment by gunjandatta** [comment]
That project was tested against v0.9.9. So I def need to retest it with the latest. Thank you logging the issue. I will get back to you as soon as I get the app to install to SPO. The instance contains 6k items, so sometimes it can timeout when deploying through Visual Studio.

**Comment by gunjandatta** [comment]
I have a "Dev" list in SPOnline with 10 items. I used the following code in the browser console:
```
(new $REST.List("Dev"))
  .Items()
  .query({
    Top: 2,
     GetAllItems: true
  })
  .execute(function(items) {
     console.log("Done");
     window.items = items;
  });
```
The network tab shows 5 requests getting executed and returns 10 items. I can test this in a SP2013 environment if you need me to.

I also tried the following code and got the same results.
```
$REST.List.getByEntityName("DevList", function(list) {
  list.Items().query({ Top:2, GetAllItems: true }).execute(function(items) {
     console.log("Done");
     window.items = items;
  });
});
```

**Comment by gunjandatta** [comment]
From your code example, you are passing back items.d.results. I don't touch the [object].d property, and add the [object.d] properties to the object itself. If you update your code to pass the "items.results", you should see all items. The "results" collection will also have the REST methods associated with it, in this case the Item Collection methods. I believe this is the reason why you are only seeing 2 results.

I'm not sure how you are coding, but I hope intellisense is available, as this can help with development. If you don't have it, or are restricted in any way, please let me know and I'll see if I can help resolve this for you.

Please let me know if this doesn't solve the issue.

**Comment by johannes-z** [comment]
I'm using `items.d.results` because I have a factory that transforms the plain json objects to useful ones (like users, dates etc.) I'm using vs code, so I do have intellisense.

**Comment by gunjandatta** [comment]
I'll update the code to combine the .d property.

**Comment by gunjandatta** [comment]
I updated the library to ensure the [object].d.results are also updated when using the GetAllItems flag. I do believe that the "results" object is similar to the [object].d.results object, so you should be able to pass the json objects over for either one. Either way, thanks for catching this one, both arrays should be updated.

Target version is 1.4.1.

Let me know if this resolves your issue.

**Comment by johannes-z** [comment]
Cool, thanks! I didn't know I *had* to use the `Items` object before. Glad I could help though :) Will try asap

**Comment by gunjandatta** [comment]
No problem. If you could close this issue out after you confirm the [object].d.results, I'd appreciate that.

Let me know how I can update this library to make life easier for you and other SP developers =)
