### ISSUE TITLE
installRequired Component - SpCfg.js - Cannot read properties of undefined.

### ISSUE THREAD

**Issue by ReconFlux** [gunjandatta/sprest#286]
The Install Required component gets frozen after clicking install. 

The error code I received is a promise reject saying: TypeError: Cannot read properties of undefined (reading 'toLowerCase').

Steps to reproduce: 

Install or reinstall an application. 

Images Attached
![stuckInstall](https://user-images.githubusercontent.com/24204923/143271466-80c17e65-1a49-4e9d-be2c-e730001e71d3.PNG)
![consoleError](https://user-images.githubusercontent.com/24204923/143271467-10241a78-92b4-4fa6-aab9-9de677d04a5c.PNG)
![ConsoleError2](https://user-images.githubusercontent.com/24204923/143271470-9e3385b5-5342-4ee1-922c-fc77a09a709a.PNG)
![ConsoleError3](https://user-images.githubusercontent.com/24204923/143271471-ea39f0e0-8e5d-4e30-ba28-9d81de12d62d.PNG)

**Comment by gunjandatta** [comment]
Added some safer code to ensure the null exception doesn't happen.

**Comment by ReconFlux** [comment]
I'm currently having this issue now.

![image](https://user-images.githubusercontent.com/24204923/143967497-f6135779-c1a0-4698-9976-68dfa1925e86.png)

**Comment by ReconFlux** [comment]
Here is the console log: 

![image](https://user-images.githubusercontent.com/24204923/143967580-28e93ddd-7df0-4ae5-91b8-dd27d64ba5b2.png)
