### ISSUE TITLE
How to remove event receiver

### ISSUE THREAD

**Issue by enti333** [gunjandatta/sprest#288]
Hello. 
Is possible with this library to remove event receivers? Of course with same user which add event receiver?
Thanks

**Comment by gunjandatta** [comment]
I wrote a blog post on the REST API and event receivers.

https://dattabase.com/blog/add-an-event-receiver-using-rest

Please let me know if this answers your question, and please close this issue if it does. Thanks for using the library.

**Comment by gunjandatta** [comment]
I am going to update the blog post to include removing event receivers. I'll update you when I do this.

**Comment by enti333** [comment]
Hello. Thank you very much. I have checked your blog and it was working for me to add an event receiver but I have didn't find how to correctly to remove it or Update for example the URL of the receiver. Thank you

**Comment by gunjandatta** [comment]
I just updated the post to include the delete option.

**Comment by gunjandatta** [comment]
Let me know if you have any other questions/issues.

**Comment by enti333** [comment]
Thank you very much for this. I will test this and let you know if it is working.:) Many Thanks:)

**Comment by gunjandatta** [comment]
Please close this issue if it answers your question.

**Comment by enti333** [comment]
THank you very much it is working!:)Thanks
