### ISSUE TITLE
Versions is undefined

### ISSUE THREAD

**Issue by jason-heiser** [gunjandatta/sprest#291]
I am trying to retrieve the version history for a list item, but the Versions property is inoperable; it is `undefined` and cannot be invoked.

```typescript
const versions = Web('https://example.com').Lists('ExampleList').getItemById(1).Versions;
console.log(versions);
```
__Result:__ `undefined`

I think obtaining the version history for list items via REST is a new feature in SharePoint 2019.

__Example:__ https://example.com/_api/web/Lists/getByTitle('ExampleList')/Items/getById(1)/versions

Visiting this URL produces a whole bunch of data that I’m trying to use in an Angular application.

Thanks again for all your tremendous work on this library.

**Comment by gunjandatta** [comment]
Can you try getting the item this way:

```js
const versions = Web('https://example.com').Lists('ExampleList').getItemById(1).Versions().executeAndWait();
console.log(versions);
```
or
```js
const versions = Web('https://example.com').Lists('ExampleList').Items(1).Versions().executeAndWait();
console.log(versions);
```

I would recommend using the asynchronous (execute) method vs the synchronous (executeAndWait) method.
```js
.execute(
  // Success
  function() { .. },

  // Error
  function() { ... }
);
```

**Comment by jason-heiser** [comment]
The examples above throw an exception because they try to invoke Versions when it actually `undefined`.

```typescript
Web('https://example.com').Lists('ExampleList').getItemById(1).Versions().execute();
// TypeError: ...Versions is not a function

Web('https://example.com').Lists('ExampleList').Items().getById(1).Versions().execute();
// TypeError: ...Versions is not a function

Web('https://example.com').Lists('ExampleList').Items(1).Versions().execute();
// TypeError: ...Versions is not a function
```

**Comment by gunjandatta** [comment]
Get the latest version (6.8.0) or the gd-sprest-bs library (9.0.2) and it will be available now. I had to update the mapper to include this new collection.

Thank you for reporting this.

**Comment by jason-heiser** [comment]
Upgrading to 6.8.0 made it work! Thank you.
