### ISSUE TITLE
Feature Request: Custom Permission Level

### ISSUE THREAD

**Issue by Dade-R** [gunjandatta/sprest#295]
Please develop a method to create and update a custom permission level when defining a new RoleAssignment. Creating a custom permission level should be defined by either calling an .add() or .remove() function, or by calling a .copy() function and specifying an existing permission level with a name for the new permission level. You could then subsequently call either .add() or .remove() on the new permission level. This feature exists OOTB in the UI and would be a great addition to this framework. Below is a complete list of each permission in a permission level.

- List Permissions
	- Manage Lists
	- Override List Behaviors
	- Add Items
	- Edit Items
	- Delete Items
	- View Items
	- Approve Items
	- Open Items
	- View Versions
	- Delete Versions
	- Create Alerts
	- View Application Pages
- Site Permissions
	- Manage Permissions
	- View Web Analytics Data
	- Create Subsites
	- Manage Web Site
	- Add and Customize Pages
	- Apply Themes and Borders
	- Apply Style Sheets
	- Create Groups
	- Browse Directories
	- Use Self-Service Site Creation
	- View Pages
	- Enumerate Permissions
	- Browse User Information
	- Manage Alerts
	- Use Remote Interfaces
	- Use Client Integration Features
	- Open
	- Edit Personal User Information
- Personal Permissions
	- Manage Personal Views
	- Add/Remove Personal Web Parts
	- Update Personal Web Parts

**Comment by Dade-R** [comment]
The goal would be to support something like:
permission.copy('Contribute', 'ContributeNoDelete');
permission.remove('ContributeNoDelete', ['Delete Items', 'Delete Versions']);

**Comment by gunjandatta** [comment]
Added a new copyPermissionLevel helper method. This method will take the following properties:

```json
{
  AddPermissions?: [number];     // Permissions to add
  Description: string;                   // Description of the permission level
  BasePermission: string;            // The name of the base permission to copy
  Order?: number;                      // The permission order
  Name: string;                          // The name of the permission level to create
  RemovePermissions?: [number];  // Permissions to not copy over
  WebUrl?: string;                     // The target site collection, current site by default
}
```

Added to v6.9.1

**Comment by gunjandatta** [comment]
```ts
// Copy and remove permissions
Helper.copyPermissionLevel({
  BasePermission: "Contribute",
  Name: "Contribute no Delete",
  Description: "Edit permissions - Delete",
  RemovePermissions: [$REST.SPTypes.BasePermissionTypes.DeleteListItems]
});

// Copy and add permissions
Helper.copyPermissionLevel({
  BasePermission: "Contribute",
  Name: "Contribute add Web",
  Description: "Edit permissions + Create Web",
  AddPermissions: [$REST.SPTypes.BasePermissionTypes.ManageSubwebs]
});
```
