### ISSUE TITLE
Custom URL Parameters for Items query

### ISSUE THREAD

**Issue by johannes-z** [gunjandatta/sprest#30]
It would be great if the `ODataQuery` Object allowed a custom url parameter, that allows you to add any kind of string to the url. In my case I want to manually add `$skiptoken=Paged=TRUE&p_ID=X` to the URL generated.

**Comment by gunjandatta** [comment]
I'll add a "Custom" property that is a "string" type that will be appended to the url.

**Comment by johndorman** [comment]
This is actually a great catch-all. Thanks.

**Comment by gunjandatta** [comment]
Target version is 1.4.6.
