### ISSUE TITLE
List renamed after re-installation when using the TitleFieldDisplayName

### ISSUE THREAD

**Issue by ndelacour** [gunjandatta/sprest#31]
I am using the Configuration.install() functionality to create the lists on the SharePoint Hostweb.
When using the TitleFieldDisplayName, in order to rename the Title column of a list and re-installing lists, the existing list is renamed, using the DisplayName for the Title column.
When removing TitleFieldDisplayName from the configuration, the list keeps his name and the list is updated as expected.

**Comment by gunjandatta** [comment]
Please try to do this w/ v1.5.7. Please send the config file to help reproduce the issue. Thank you.

**Comment by gunjandatta** [comment]
I rewrote the automation class, based on the latest intellisense. I believe issue should be resolved. Please reopen this issue and provide the sample config file so I can further troubleshoot the issue.

Target v1.7.2
