### ISSUE TITLE
Views on a list not created/update when there is no space in the Title of the list.

### ISSUE THREAD

**Issue by ndelacour** [gunjandatta/sprest#32]
I am using the Configuration.install() to create the lists, with their views on the Hostweb of my application. I give the list a title without any space (' ') in the title, like <<Title: "TestProject">> the views are not created for this list. When adding a space into the title, like <<Title: "Test Project">> the views are created correctly.
It seems that the space is necessary to be able to create the views.

**Comment by gunjandatta** [comment]
Please try to do this w/ v1.5.7. Please send the config file to help reproduce the issue. Thank you.

**Comment by gunjandatta** [comment]
I rewrote the automation class, based on the latest intellisense. I believe issue should be resolved. Please reopen this issue and provide the sample config file so I can further troubleshoot the issue.

Target v1.7.2
