### ISSUE TITLE
Creation/updating view is using the title of the view rather than the staticName

### ISSUE THREAD

**Issue by ndelacour** [gunjandatta/sprest#33]
When updating a view, the view is selected based on the title and not on the staticName. This causes an issue when the site is installed with another language as English, when we would like to update the default view 'AllItems'. The view name is translated by SP, so using 'All Items' creates a new view called 'All Items' instead of updating the current view with the staticName 'AllItems' but the Name depending on the language of the site collection.
A workaround is to create a configuration file for each language instead and selecting the one based on the language before executing the .install().

**Comment by gunjandatta** [comment]
Please try to do this w/ v1.5.7. Please send the config file to help reproduce the issue. Thank you.

**Comment by gunjandatta** [comment]
I rewrote the automation class, based on the latest intellisense. I believe issue should be resolved. Please reopen this issue and provide the sample config file so I can further troubleshoot the issue.

Target v1.7.2
