### ISSUE TITLE
Typescript semantic errors

### ISSUE THREAD

**Issue by Jlopean** [gunjandatta/sprest#43]
Hi  (great looking tool)
Quick question; i am trying to test this out. however, whenever i use gulp to build i get 430 typescript semantic errors. anyway to ignore these errors? or should i have use some sort of setting somewhere?

example error
C:/.../gd-sprest/build/definitions/list/list.d.ts(21,56): error TS7006: Parameter 'IList' implicitly has an 'any' type.
[12:10:43] TypeScript: 430 semantic errors

**Comment by gunjandatta** [comment]
What version of the library and TypeScript do you have? I've tested the latest (v1.9.4) with TypeScript v2.5.2 and it builds fine. I believe the library requires TypeScript v2.3.4. Could you send a hello world example project so I can recreate the issue and further troubleshoot.

Thanks for reporting this issue.

**Comment by Jlopean** [comment]
Hi, 
i simply added this one line ->  import { List, Types } from "gd-sprest"; into my tsx file
this is my package.json file
`{
  "name": "lab-ux",
  "version": "0.0.0",
  "description": "lab",
  "main": "server.js",
  "author": {
    "name": "Jlopean"
  },
  "scripts": {
    "start": "node server.js",
    "dev": "node ./www/server.js",
    "dev:linux": "NODE_ENV=development node ./www/server.js",
    "dev:windows": "SET NODE_ENV=development&& node www\\server.js",
    "build": "gulp"
  },
  "browserify-shim": {},
  "dependencies": {
    "errorhandler": "^1.5.0",
    "es6-promise": "^4.1.1",
    "express": "^4.13.4",
    "gd-sprest": "^1.9.4",
    "office-ui-fabric-react": "^4.40.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1"
  },
  "devDependencies": {
    "@types/errorhandler": "0.0.30",
    "@types/express": "^4.0.36",
    "@types/node": "^8.0.12",
    "@types/react": "^15.0.38",
    "@types/react-dom": "^15.5.1",
    "@types/react-router": "^4.0.14",
    "@types/react-router-dom": "^4.0.7",
    "browserify": "^14.4.0",
    "browserify-shim": "^3.8.12",
    "event-stream": "^3.3.1",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-cssmin": "^0.2.0",
    "gulp-if": "^2.0.0",
    "gulp-less": "^3.0.5",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.6.0",
    "gulp-typescript": "^3.2.0",
    "gulp-uglify": "^3.0.0",
    "rimraf": "^2.5.2",
    "run-sequence": "^2.0.0",
    "stream-browserify": "^2.0.1",
    "typescript": "^2.4.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "vinyl-transform": "^1.0.0",
    "yargs": "^8.0.2"
  }
}
`

**Comment by gunjandatta** [comment]
Apologies for the additional questions, but could you send your gulp and server.js files? I copied your package file and created a "server.js" file with the following code:
```
var $REST = require("gd-sprest");

var requestInfo = (new $REST.Web("https://my.sharepoint.com/sites/dev")).Lists("Site Assets").Items().query({
    Filter: "ID gt 0"
}).getInfo();

console.log(requestInfo);
```

Running "npm run start" gave me this as an output:
```
PS C:\projects\dev> npm run start

> dev@0.0.0 start C:\projects\dev
> node server.js

{ data: undefined,
  method: 'GET',
  url: 'https://my.sharepoint.com/sites/dev/_api/web/Lists/getByTitle(\'Site Assets\')/Items/?$filter=ID gt 0' }
PS C:\projects\dev>
```

**Comment by Jlopean** [comment]
Hi (thanks for looking into this), this is the starter kit i used : https://github.com/toddlucas/react-tsx-starter 
-  I then installed gd-sprest
- added import { List, Types } from "gd-sprest";  to a tsx file 
- run 'gulp' to build and you should receive the errors i mentioned

**Comment by Jlopean** [comment]
fyi. in tsconfig i changed "noImplicitAny": false.

It now ignores the typescript semantic errors ;-)

**Comment by gunjandatta** [comment]
I updated the noImplicitAny value in the tsconfig from "true" to "false" and ran gulp. Is that an issue?
```
{
    "compilerOptions": {
        "jsx": "react",
        "module": "commonjs",
        "noImplicitAny": false
    }
}
```

**Comment by gunjandatta** [comment]
Literally just came to the same conclusion. You beat me to it. :)

Thanks again for reporting this issue.
