### ISSUE TITLE
Void is not assignable to parameter of type boolean

### ISSUE THREAD

**Issue by Jlopean** [gunjandatta/sprest#44]
Hi, (me again)
I tried to add Data.tsx from your sample project : sprest-fabric-react/SPREST.FabricReact/SPREST.FabricReact.UX/src/components/List/data.tsx

![image](https://user-images.githubusercontent.com/5894555/30141642-0e309882-93c0-11e7-97a0-924d2d0ab30a.png)

unfortunately i get the following error. error TS2345: Argument of type '(items: IListItems) => void' is not assignable to parameter of type 'boolean'.

I can change "(items:Types.IListItems)" to "(items:any)", then it compiles. What do you recommend?

`   // Execute the request
                    .execute(**(items:Types.IListItems)** => {
                        let data: IData[] = [];

                        // Parse the items
                        for (let item of items.results) {
                            // Add the item to the data array
                            data.push({
                                Title: item["Title"],
                                County: item["County"],
                                State: item["State"]
                            });
                        }`

**Comment by gunjandatta** [comment]
I need to update the project, it was written prior to the intellisense re-write. Remove the "Type" declaration, as it's no longer needed.

I'll update the code in this solution later today.

**Comment by gunjandatta** [comment]
I updated the project, so it's using the latest library. I would recommend checking out [this post](http://dattabase.com/sharepoint-react-webparts/) going over the new webpart components in the gd-sprest-react library, or this [GitHub site](https://github.com/gunjandatta/sprest-webparts) for better code examples.

Thanks again for reporting this. Let me know if you have any other issues/comments.

**Comment by Jlopean** [comment]
thanks!
