### ISSUE TITLE
Question: Web getsubwebsfilteredforcurrentuser with select & chaining

### ISSUE THREAD

**Issue by jpalo** [gunjandatta/sprest#47]
Hi,
I can query subwebs Titles in SharePoint Online using query such as `/_api/web/getsubwebsfilteredforcurrentuser(nwebtemplatefilter=-1,nconfigurationfilter=-1)?$select=Title`. 

How would I combine the Select when using SPREST? It is not allowed after so query such as `web.getSubwebsFilteredForCurrentUser(-1, -1).query({Select: ["Title", "Url"]}).execute()` doesn't work.

Also, cannot chain anything, as getting error "$REST.Web(...).getSubwebsFilteredForCurrentUser(...).execute(...).Lists is not a function", e.g., when trying this:     
```
$REST.Web().getSubwebsFilteredForCurrentUser(-1, -1).execute()
    .Lists("pages").Items().query({Select: ["Title", "ServerRelativeUrl"]}).execute();
```

but also all samples in Wiki, such as this give similar error
```
// Get the current web
$REST.Web()
    // Get the Field Collection
    .Fields()
    // Query for all fields with the name of 'Title'
    .query({
        Filter: "Title eq 'Title'"
    })
    // Execute this request
    .execute()
    // Get the 'Dev' List
    .Lists("Dev")
    // Get the items
    .Items()
    // Execute this request after the previous one completes
    .execute(true)
    // Get root folders
    .Folders()
    // Execute this request after the previous one completes
    .execute(true)
    // Wait for the requests to complete
    .done(function(fields, items, folders) {
        // This code will execute after all requests have completed
    });
```

Am I missing something essential especially in the second chaining issue?

**Comment by gunjandatta** [comment]
I wasn't aware of this method in the documentation. I will update the mapper class and intellisense to include this one.

**Comment by gunjandatta** [comment]
How exactly are you using the library? Loaded directly in the SP page, running statements from the browser console? In JavaScript/TypeScript in a script? In NodeJS to get the request information?

I've been trying to update the wiki pages from the latest changes, so I apologize for anything not working. I actually found a bug in the intellisense from this issue, so thank you for reporting this. The $REST intellisense wasn't update to reflect a recent change, which is now fixed in v1.9.7.

If you are executing live requests in the browser console, then you want to use the "executeAndWait()" method so it returns the request.

**Browser Console:**
```
var webs = $REST.Web().getSubwebsFilteredForCurrentUser(-1, -1).executeAndWait()
```

If this is within an application, then the intellisense should help out with the available commands. The "getsubwebsfilteredforcurrentuser" method is a post request, so the intellisense won't let you select query or other methods since this method doesn't allow chaining of sub-properties or methods.

**JavaScript:**
```
var $REST = require("gd-sprest");

// Get the current web
$REST.Web()
   // Get the sub webs
   .getSubwebsFilteredForCurrentUser(-1, -1)
   // Execute the request
   .execute(webs => {
       // webs contains the output of the request
   });
```

**TypeScript:**
```
import { Web } from "gd-sprest";

// Get the current web
(new Web())
   // Get the sub webs
   .getSubwebsFilteredForCurrentUser(-1, -1)
   // Execute the request
   .execute(webs => {
       // webs contains the output of the request
   });
```

I never created an output interface for this method, but will ensure I add this now. v1.9.7 (available now) has the fix for the intellisense of the $REST object. v1.9.8 (available later today) will have the intellisense for this method.

**Comment by gunjandatta** [comment]
I hope this info helps answer your question. Please let me know if you are still having issues, and I'll happily assist.

**Comment by jpalo** [comment]
Thank you! getSubwebsFilteredForCurrentUser being POST explains alot. I'm using JavaScript.

What I ended up doing just to get things moving was to create separate Deferred functions for both  `web.getSubwebsFilteredForCurrentUser(-1, -1).execute((webs) =>{ // ... }` and `web.Lists("pages").Items().query({Select: ["Title", "FileRef"]}).execute((pages) => { // ... }`. Not sure if there would be less verbose way of doing it, i.e., directly getting jQuery Deferred promise from SPREST .execute().

```
var promises = [];
promises.push(getSubWebs(web));
promises.push(getPages(web));
    
$.when.apply($, promises).then(function() {        
    dfd.resolve(arguments[0].concat(arguments[1]));
});
```

and

```
function getSubWebs(web) {
    var dfd = $.Deferred();
    var jsonData = [];

    web.getSubwebsFilteredForCurrentUser(-1, -1)
    .execute((webs) => {
        for(var i = 0; i < (webs.results ? webs.results.length : 0); i++) {                
            jsonData.push({ 
                "text": webs.results[i].Title, 
                "href": webs.results[i].ServerRelativeUrl,
                "isLazy": true,
                "isFolder": true
            });
        }

        dfd.resolve(jsonData);
    });

    return dfd.promise();
}

function getPages(web) {
    var dfd = $.Deferred();
    var jsonData = [];

    web.Lists("pages").Items().query({Select: ["Title", "FileRef"]})
    .execute((pages) => {
        for(var i = 0; i < (pages.results ? pages.results.length : 0); i++) {                
            jsonData.push({ 
                "text": pages.results[i].Title, 
                "href": pages.results[i].FileRef                
            });
        }

        dfd.resolve(jsonData);
    });

    return dfd.promise();
}
```

**Comment by gunjandatta** [comment]
I thought you may ask about es6-promises, I added the "then" method to the base class last night, which will return an es6-promise. Check out this [wiki post](https://github.com/gunjandatta/sprest/wiki/Full-Control-of-Request-Execution-Order) for more info on the "execute" method.

You are correct, it's a get, I'll update the mapper and set the "type", so you can chain it. It returns an array of web info, which is not the same as the web object. I'm not sure what you could chain against it.

**Comment by gunjandatta** [comment]
Version 2.0.1 has the updated mapper class, so you can now query the web info.
```
$REST.Web().WebInfos().query({ Select: ["Title", "ServerRelativeUrl"] }).executeAndWait()
$REST.Web().getSubwebsFilteredForCurrentUser(-1, -1).query({ Select: ["Title", "ServerRelativeUrl"] }).executeAndWait()
```

Taking your example, it can be written as:
```
// Get the current web
var web = $REST.Web();

// Get the sub-webs
web.getSubwebsFilteredForCurrentUser(-1, -1)
   // Query the subwebs
   .query({ Select: ["Title", "ServerRelativeUrl"] })
   // Execute the request
   .then(webs => {
      // Parse the web information
      for(var i=0; i<webs.results.length; i++) {
         var web = webs.results[i];
      }
   }, () => {
      console.log("Error: " + request.response);
   });

// Get the pages
web.Lists("pages")
   // Query the items
   .Items().query({ Select: ["Title", "FileRef"] })
   // Execute the request
   .then(pages => {
      // Parse the pages
      for(var i=0; i<pages.results.length; i++) {
         var page = pages.results[i];
      }
   }, (request) => {
      console.log("Error: " + request.response);
   });

// Wait for the requests to complete
web.done(function(pages, webs) {
   // Wait for the requests to complete
   The "done" method will wait for all requests of the base object (web) to complete. It will pass the requests based on the order of execution. There is a flag that allows you to execute them in order, if needed. It's explained in the wiki post.
});
```

**Comment by gunjandatta** [comment]
You may want to look at [cross-site requests](https://github.com/gunjandatta/sprest/wiki/Cross-Site-Collection-Requests) as well, in case you want to execute a "Post" request against a different site collection w/in the same domain. This is useful when you the OData filter limitations are at play, and you need to use CAML. Examples would be the IsNull operator or using <Today /> <Me /> as values.

I hope this info answers the initial question. If so, please close out this issue. If you have questions, feel free to post them here or email me directly.

Thanks for reporting this issue.

**Comment by jpalo** [comment]
Yes, thank you for a nice concise library and effort in ths matter!

**Comment by jpalo** [comment]
Actually, looks like both are now missing the return value. REST query itself is executed fine and returns values.

```
web.getSubwebsFilteredForCurrentUser(-1, -1)
   // Query the subwebs
   .query({ Select: ["Title", "ServerRelativeUrl"] })
   // Execute the request
   .then(webs => { // webs is undefined
```
while the previous works
```
    web.getSubwebsFilteredForCurrentUser(-1, -1)
    .execute((webs) => { // webs is ok
```

**Comment by jpalo** [comment]
Sorry for the close/open hassle. 

The sample you provided didn't work that well as webs was always undefined, not sure if it is a bug in the library, or just due to quick sample you wrote.

```
web.getSubwebsFilteredForCurrentUser(-1, -1)
   // Query the subwebs
   .query({ Select: ["Title", "ServerRelativeUrl"] })
   // Execute the request
   .then(webs => { // webs is undefined
```

This with .executes and .done it now works great like this:
```
// get subwebs
web.getSubwebsFilteredForCurrentUser(-1, -1)
.query({ Select: ["Title", "ServerRelativeUrl"] })
.execute();

// get pages
web.Lists(pagesListName).Items()
.query({Select: ["Title", "FileRef"]})
.execute();
    
web.done((webs, pages) => { // ...
```

**Comment by gunjandatta** [comment]
Are you using the latest version? I was able to execute this in SPO:
```
$REST.Web().getSubwebsFilteredForCurrentUser(-1, -1).then(function(webs) { debugger; });
```

The "webs" variable had the correct info. Please re-open this issue if you are having issues.
Thanks and I'm glad you like the library. If you have any issues/questions, I'm always happy to help others.
