### ISSUE TITLE
Search query functionality in SharePoint Hosted AddIn creates wrong url

### ISSUE THREAD

**Issue by ndelacour** [gunjandatta/sprest#56]
When using the search functionality within a SharePoint Hosted AddIn, the url of the REST call is not correct. It seems that the way the search is handled in this case is an MS exception. I found the following article describing the same issue and the solution [here](http://www.migee.com/2016/01/15/sharepoint-app-add-in-search-requests-error-cannot-find-resource-for-the-request-search/)

In order to fix this issue, I added a check in the creation of the url: (file : targetInfo.js)
`            //Check if this is part of the search
            if (this.targetInfo.endpoint.startsWith("search")) {
                // Set the request url
                this.requestUrl = template
                    .replace(/{{Url}}/g, lib_1.ContextInfo.webAbsoluteUrl)
                    .replace(/{{EndPoint}}/g, endpoint)
                    .replace(/{{TargetUrl}}/g, "");
            } else {
                // Set the request url
                this.requestUrl = template
                    .replace(/{{Url}}/g, lib_1.ContextInfo.webAbsoluteUrl)
                    .replace(/{{EndPoint}}/g, "SP.AppContextSite(@target)/" + endpoint)
                    .replace(/{{TargetUrl}}/g, "@target='" + this.targetInfo.url + "'");
`
This allows the query to be executed, but made me run into a second issue, the way the query was executed was considered 'not save'. Therefore I changed the way to supply the parameters to the query : (file : methodInfo.js)
`'// Set the url
            if (this.methodInfo.name === "query") {
                url += params.length > 0 ? "?" + params.replace(/, $/, "") + "" : "";
            } else {
                url += params.length > 0 ? "(" + params.replace(/, $/, "") + ")" : "";
            }`
This allows me to run the search query from a SharePoint hosted Add-In.
I did not ran any additional tests yet, to see if I caused any impact on your way of executing the queries...

**Comment by gunjandatta** [comment]
I'm slightly confused here, from the article it's saying to execute the request against the App Web. By default, the search object will target the current web, unless the global flag $REST.DefaultRequestToHostFl flag is set to "true". This flag is what adds the SP.AppContextSite(@target) to the request, per the article. If the flag is set to "false", then it should execute against the SP web. If this isn't happening then that would be a pretty big bug.

**Comment by ndelacour** [comment]
Good point, for the first part, sorry about that. Since all requests are for the host-web, I set is by default to true as first statement in the Add-In. I will put it to false before calling the search, and set it back to true just after.
Using postquery the second issue (query not save) should not exist, so I will switch to that call, but will test it tomorrow at work to confirm the issue, with the DefaultRequestToHostFI flag set to false.

**Comment by gunjandatta** [comment]
Thanks for looking into this. Glad it's not a bug (hopefully) :)

**Comment by ndelacour** [comment]
I tested with the postquery, the solution with the $REST.DefaultRequestToHostFl  works fine. The trouble with the searchquery stays: I get the following error when using the generated URL:
A potentially dangerous Request.Path value was detected from the client (:).
(query string used : /_api/search/query(Querytext='Contenttype:Milestone*'))
Changing it towards the following url works fine for me:
/_api/search/query?Querytext='Contenttype:Milestone*'

I  do not know if this is due to our environment. In order change the url, I had to make some changes, which I can share is you would like.

I am willing to switch to the postquery, but I have difficulties to get the right syntax for the SelectProperties. I tried several combinations, but I keep on getting a 400 (Bad Request). Below the list of my tests:
`(new Search()).postquery({ Querytext: "Contenttype:Milestone*" }).execute(results => { });` -> this works OK
`(new Search()).searcquery({ Querytext: "Contenttype:Milestone*", SelectProperties: 'TaskDueDateOWSDATE,Title' }).execute(results => { });` -> this works OK after my applying my changes for the URL
`(new Search()).postquery({ Querytext: "Contenttype:SafranMilestone*", SelectProperties: 'TaskDueDateOWSDATE,Title' }).execute(results => { });` -> 400 (Bad Request) An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.
`(new Search()).postquery({ Querytext: "Contenttype:SafranMilestone*", SelectProperties: {'results': ['Title','ContentSource','DisplayAuthor']} }).execute(results => { });` -> Compilation error : error TS2345: Argument of type '{ Querytext: string; SelectProperties: { 'results': string[]; }; }' is not assignable to parameter of type 'SearchRequest'.
  Types of property 'SelectProperties' are incompatible.
    Type '{ 'results': string[]; }' is not assignable to type 'String'.
      Object literal may only specify known properties, and ''results'' does not exist in type 'String'.
`(new Search()).postquery({ Querytext: "Contenttype:SafranMilestone*", SelectProperties: "{'results': ['Title','ContentSource','DisplayAuthor']}" }).execute(results => { });` -> 400 (Bad Request) : An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.

After some debugging, I got the feeling that in the postquery parameters, the SelectProperties are not correctly formatted : 
`"SelectProperties":{\"results\": [\"Title\",\"ContentSource\",\"DisplayAuthor\"]}`
instead of:
`"SelectProperties":{\"results\": [\"Title\",\"ContentSource\",\"DisplayAuthor\"]}`

If I remove the quotes in the dev browser, the statement is executed OK.

This issue seems to be true for the params indicated in your documentation as Array. I tried to see where the code goes wrong, but I have not been able to find it (yet).

**Comment by gunjandatta** [comment]
@ndelacour Thanks for looking into this.

To address the first issue related to how the query is applied to the url, I updated the searchquery and suggest methods in the search class, and changed how the parameters are being applied to the url.

For the issue with the "SelectProperties", I was able to execute the following w/out any issues in a SharePoint Online environment.
```
$REST.Search().postquery({ Querytext: "Contenttype:Item", SelectProperties: { results: ["Title", "ID", "ContentSource"] } }).executeAndWait()
```

The fix is in v2.0.3. Let me know if you are still having issues w/ the postquery.

**Comment by ndelacour** [comment]
For the searchquery, the new version (2.0.3) seems to be working. I can not work on the SP environnement directly today, but using the get created in my node.js environment on the SharePoint production, there are no errors.
For the postquery, I was still having troubles. The example you gave was giving the build error as described above. I found a quick-n-dirty solution for this : in the complexTypes.d.ts file I changed the type for the SelectProperties:
before (not building):
`    SelectProperties?: String;
`
after (building OK):
`    SelectProperties?: Object;
`
This resolved the building issue for me.

**Comment by gunjandatta** [comment]
Yup, you're right. The intellisense needs to be updates. I'll review the properties.

Note - There is an IResults<T> interface that can be used for values w/ the format { results: T }

**Comment by gunjandatta** [comment]
Target is v2.0.4 for the updated intellisense. Thanks for looking into this.

FYI - The "ComplexTypes" class can be imported and contains the interfaces for the search results. Let me know if there are any other issues.

**Comment by ndelacour** [comment]
I tested v2.0.4 and all issues have been resolved. Merci pour ton aide.
