### ISSUE TITLE
REST API & filter URL issue in AddIn mode

### ISSUE THREAD

**Issue by ndelacour** [gunjandatta/sprest#71]
Within an AddIn application ($REST.DefaultRequestToHostFl = true), I am running into a URL error, in the case that the this.targetInfo.endpoint includes already a '?'. I found this error when using the save functionality of the itemForm component from the gd-sprest-react library.
The solution would be to replace the following code:
`this.requestUrl = lib_1.ContextInfo.webAbsoluteUrl + "/_api/SP.AppContextSite(@target)/" + url[1] +
                    (this.targetInfo.endpoint ? "/" + this.targetInfo.endpoint : "") +
                    "?@target='" + url[0] + "'";`
with this one:
`                this.requestUrl = lib_1.ContextInfo.webAbsoluteUrl + "/_api/SP.AppContextSite(@target)/" + url[1] +
                    (this.targetInfo.endpoint ? "/" + this.targetInfo.endpoint : "") + ((this.targetInfo.endpoint.indexOf("?")==-1) ? "?" : "&" ) +
                    "@target='" + url[0] + "'";
`
This checks if there is already a ? in the endpoint, and introduce a '&' instead of the '?'.
I tested this solution with the indicated component and seems to work OK.

**Comment by gunjandatta** [comment]
The code changes for the batch operations included an update to the targetinfo.endpoint variable. Let me double check this against this method. Thanks for the code fix. I'll get this fixed asap.

**Comment by gunjandatta** [comment]
I applied your code fix and cleaned up the method. Thanks again for the help on this. The target version is v2.2.0. Let me know if there are any other issues.

**Comment by gunjandatta** [comment]
I'll close this issue out, but please re-open it if you have issues.
