### ISSUE TITLE
URL used for PeoplePicker in ItemForm for AddIn (DefaultRequestToHostFI =true)

### ISSUE THREAD

**Issue by ndelacour** [gunjandatta/sprest#75]
When using the ItemForm from an application (AddIn), for a list from the WebHost (DefaultRequestToHostFI =true), the query called to retrieve the users (SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.ClientPeoplePickerSearchUser) returns the following error: 
> Cannot find resource for the request SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.ClientPeoplePickerSearchUser

I think that the `SP.AppContextSite(@target)` part of the url should be removed. for this query:

Current call
> /_api/SP.AppContextSite(@target)/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.ClientPeoplePickerSearchUser?@target=%27https://xxxxx.sharepoint.com/sites/APPS%27

Call which should be working
> /_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.ClientPeoplePickerSearchUser

It is not possible to set the flag DefaultRequestToHostFI  to 'false', since the other calls should not be impacted/we do not have the possibility to do this without impacting the ItemForm

**Comment by gunjandatta** [comment]
I'm looking into this, but make sure you are using the latest 1.6.9. I made a bunch of fixes related to the User Field and the Item Form.

**Comment by gunjandatta** [comment]
This is an issue w/ specific endpoints. The library has a "defaultToWebFl" which is set by the endpoints that must target the current web. This flag was not being passed to the target information class. I've made an update to ensure the logic will use this flag to override and target the current web regardless of the DefaultRequestToHostFl flag.

**Comment by gunjandatta** [comment]
I added a new property to the target info: "overrideDefaultRequestToHostFl", the other defaultToWebFl was used for something else. I updated the people picker class to set this flag, and tested it in the app web. Updating the gd-sprest library to v2.2.4 should fix it, but I updated the gd-sprest-react packages and published v1.7.0 just in case.

I ran the search and a couple other apis in the app web, and wasn't able to see this issue with search or social endpoints. If you run into this again, just let me know and I'll add the flag to the appropriate api.

Please close this issue out if it's fixed. Thanks for reporting this issue.

**Comment by ndelacour** [comment]
Thanks for this quick resolution. I updated my program and deployed it towards o365. It is working fine!
